### PR TITLE
Plot Graph bug fixed

### PR DESCRIPTION
**Pull request by sadrasabouri**
#### Reference Issues/PRs
#17

### CODE REVIEW

**Comment by sadrasabouri** [comment]
Would you please take a quick look at this PR, @sepandhaghighi?

**Comment by sepandhaghighi** [comment]
@sadrasabouri What happened in `CI / build (windows-latest, 3.6)`?

**Comment by sadrasabouri** [comment]
> @sadrasabouri What happened in `CI / build (windows-latest, 3.6)`?

I believe it's related to some dependency issues (probably from `networkx`)

**Comment by sepandhaghighi** [comment]
> > @sadrasabouri What happened in `CI / build (windows-latest, 3.6)`?
> 
> I believe it's related to some dependency issues (probably from `networkx`)

Do you have any plans to solve it?
Because it will lead to other tests canceling

**Comment by sadrasabouri** [comment]
> > > @sadrasabouri What happened in `CI / build (windows-latest, 3.6)`?
> > 
> > 
> > I believe it's related to some dependency issues (probably from `networkx`)
> 
> Do you have any plans to solve it? Because it will lead to other tests canceling

I removed Python 3.5 and 3.6 from the tests. It seems that windows have some problems with Python 3.6 and I decided to just keep Python 3.7, 3.8 and 3.9.

**Review by sepandhaghighi — APPROVED** [review]

**Pull request merged**
